import { useQuery } from '@tanstack/react-query';
import { adminApi } from '../../api';
import { formatDate, formatNumber } from '../../utils';
import { CardSkeleton } from '../../components/common/LoadingSpinner';
import { Bot, Activity, Zap, CheckCircle, XCircle, Clock } from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
} from 'recharts';

export default function AdminAIMonitoringPage() {
  const { data: aiData, isLoading } = useQuery({
    queryKey: ['adminAI'],
    queryFn: () => adminApi.getAiMonitoring().then(r => r.data.data),
    refetchInterval: 30_000,
  });

  const barData = (aiData?.intentBreakdown || []).map((i: any) => ({
    intent: i.intent?.replace(/_/g, ' ') || 'Unknown',
    count: i._count?.intent || 0,
  }));

  return (
    <div className="space-y-6 max-w-7xl">
      <div className="flex items-start sm:items-center gap-3 flex-wrap">
        <div className="w-10 h-10 bg-indigo-100 rounded-xl flex items-center justify-center">
          <Bot className="w-5 h-5 text-indigo-600" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-gray-900">AI Agent Monitoring</h1>
          <p className="text-sm text-gray-500 flex items-center gap-1.5">
            <Activity className="w-3.5 h-3.5 text-green-500 animate-pulse" /> Live — auto-refreshes every 30s
          </p>
        </div>
      </div>

      {/* MOCK badge */}
      <div className="bg-indigo-50 border border-indigo-200 rounded-xl p-3 flex items-center gap-3">
        <span className="text-xs font-bold bg-indigo-500 text-white px-2 py-0.5 rounded">MOCK AI</span>
        <p className="text-xs text-indigo-800">AI responses are generated by the mock provider. Set <code className="bg-indigo-100 px-1 rounded">AI_PROVIDER=GRANITE</code> and configure IBM watsonx credentials to switch to real IBM Granite inference.</p>
      </div>

      {isLoading ? (
        <div className="grid md:grid-cols-2 gap-4">{[1,2,3,4].map(i => <CardSkeleton key={i} lines={3} />)}</div>
      ) : (
        <>
          {/* Agent status cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {(aiData?.agents || []).map((agent: any) => (
              <div key={agent.name} className="card hover:shadow-md transition-shadow">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-indigo-100 rounded-xl flex items-center justify-center">
                      <Bot className="w-5 h-5 text-indigo-600" />
                    </div>
                    <div>
                      <p className="font-semibold text-gray-900 text-sm leading-tight">{agent.name}</p>
                      <p className="text-xs text-gray-400">
                        {agent.lastExecution ? `Last: ${formatDate(agent.lastExecution)}` : 'Never executed'}
                      </p>
                    </div>
                  </div>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                    agent.status === 'ACTIVE' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'
                  }`}>{agent.status}</span>
                </div>
                <div className="grid grid-cols-3 gap-2 text-center">
                  <div className="bg-gray-50 rounded-lg p-2">
                    <p className="text-lg font-bold text-gray-800">{formatNumber(agent.executionCount)}</p>
                    <p className="text-xs text-gray-400">Runs</p>
                  </div>
                  <div className="bg-green-50 rounded-lg p-2">
                    <p className="text-lg font-bold text-green-700">{Math.round(agent.successRate * 100)}%</p>
                    <p className="text-xs text-gray-400">Success</p>
                  </div>
                  <div className="bg-blue-50 rounded-lg p-2">
                    <p className="text-lg font-bold text-blue-700">{agent.avgExecutionMs}ms</p>
                    <p className="text-xs text-gray-400">Avg</p>
                  </div>
                </div>
                {/* Health bar */}
                <div className="mt-3">
                  <div className="flex justify-between text-xs text-gray-400 mb-1">
                    <span>Health</span><span>{Math.round(agent.successRate * 100)}%</span>
                  </div>
                  <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all ${
                        agent.successRate >= 0.9 ? 'bg-green-500' :
                        agent.successRate >= 0.7 ? 'bg-amber-500' : 'bg-red-500'
                      }`}
                      style={{ width: `${agent.successRate * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Intent distribution */}
          {barData.length > 0 && (
            <div className="card">
              <h3 className="font-semibold text-gray-900 mb-4">Query Intent Distribution</h3>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={barData} margin={{ left: -10 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="intent" tick={{ fontSize: 11 }} />
                  <YAxis tick={{ fontSize: 11 }} />
                  <Tooltip />
                  <Bar dataKey="count" fill="#6366f1" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}

          {/* Recent requests */}
          {aiData?.recentRequests?.length > 0 && (
            <div className="card">
              <h3 className="font-semibold text-gray-900 mb-4">Recent AI Requests</h3>
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {aiData.recentRequests.map((req: any, i: number) => (
                  <div key={i} className="flex items-start justify-between p-3 hover:bg-gray-50 rounded-xl border border-gray-50">
                    <div className="flex items-start gap-3 min-w-0">
                      <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 ${
                        req.success ? 'bg-green-100' : 'bg-red-100'
                      }`}>
                        {req.success
                          ? <CheckCircle className="w-3.5 h-3.5 text-green-600" />
                          : <XCircle className="w-3.5 h-3.5 text-red-500" />
                        }
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm text-gray-700 truncate">{req.query}</p>
                        <p className="text-xs text-gray-400">{req.user?.email} · {req.intent}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 ml-4 flex-shrink-0">
                      <span className="text-xs text-gray-400 flex items-center gap-1">
                        <Clock className="w-3 h-3" /> {req.executionMs}ms
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Pipeline stats */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="card text-center">
              <Zap className="w-8 h-8 text-indigo-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-900">{formatNumber(aiData?.totalRequests || 0)}</p>
              <p className="text-xs text-gray-500">Total AI Requests</p>
            </div>
            <div className="card text-center">
              <CheckCircle className="w-8 h-8 text-green-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-900">{aiData?.overallSuccessRate ? `${Math.round(aiData.overallSuccessRate * 100)}%` : '—'}</p>
              <p className="text-xs text-gray-500">Overall Success Rate</p>
            </div>
            <div className="card text-center">
              <Clock className="w-8 h-8 text-blue-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-900">{aiData?.avgExecutionMs ? `${Math.round(aiData.avgExecutionMs)}ms` : '—'}</p>
              <p className="text-xs text-gray-500">Avg Response Time</p>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
